### ISSUE TITLE
Cannot save as CWS - Mac OS 10.14.6 - Chitubox 1.6.3 

### ISSUE THREAD

**Issue by champuru** [opensourcemanufacturing/Nova3D-Elfin-Chitubox-Plugin#3]
Hello, I followed the instructions. After slicing, I do not have the option to save as CWS. I have included two screenshots for reference (Java version, Save as selection, and Profiles). I even uninstalled chitubox, removed stored preferences and all saved information. Then reinstalled chitubox, installed the plugin, and imported the profile with the same results. Any guidance or assistance is greatly appreciated.

<img width="530" alt="Screen Shot 2020-04-12 at 12 18 28 PM" src="https://user-images.githubusercontent.com/43624692/79078639-90037e80-7cbe-11ea-8fff-f771258e5821.png">
<img width="443" alt="Screen Shot 2020-04-12 at 12 17 46 PM" src="https://user-images.githubusercontent.com/43624692/79078653-9bef4080-7cbe-11ea-901d-c8123d513073.png">
<img width="783" alt="Screen Shot 2020-04-12 at 1 06 04 PM" src="https://user-images.githubusercontent.com/43624692/79078656-a1e52180-7cbe-11ea-978b-029dde3742b3.png">

**Comment by champuru** [comment]
I managed to manually install the plugin. Now, I have the same problem as Issue #2. After slicing and selecting save. I choose filename, location and save. Chitubox reports "Converting format" and hangs.  I have attached a screenshot for reference, but I will close this issue to avoid duplicates.

<img width="511" alt="Screen Shot 2020-04-12 at 2 08 31 PM" src="https://user-images.githubusercontent.com/43624692/79079992-3a7f9f80-7cc7-11ea-85c2-19918fc75350.png">

**Comment by X3msnake** [comment]
I'll upload tonight a version that has the runtime for Linux.

**Comment by X3msnake** [comment]
Beta version released here. it has already been tested and it is working but do please run it the first time without plate and vat. and as always this is prodived to use at your own risk. 

Let me know your results so i can promote this to release candidate.

Good printing ;)

https://github.com/opensourcemanufacturing/Nova3D-Elfin-Chitubox-Plugin/raw/master/Nova3DPlugin_200316_beta.chplugin

**Comment by nisshan-x** [comment]
I tried Nova3DPlugin_200316_beta.chplugin, but couldn't save as CWS...

My environment:

CHITUBOX : V1.6.3
macOS : High Sierra (10.13.6)
```
$ java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```
So it seems the same problem still happens to me...

**Comment by nisshan-x** [comment]
I found a way to solve it by myself. So I share the way for others who face the same problem.

1. Start Chitubox
2. Open menu on left-top
3. Open help -> plugin
4. Press Import Plugin and choose Nova3DPlugin_200316_beta.chplugin

Then save-as-csw appears. Phew!

It's ok for me to close this reopened issue.

**Comment by featherJ** [comment]
Hello, Thanks for your work.

 I found that I need to add "cd $(dirname $0)" into file "macshell.command" like this:

```
#!/bin/bash

cd $(dirname $0)

echo "helloworld " ~$(dirname $0)/ >> ~/Library/Preferences/Chitubox/zipTmpDir/welcome.txt

Java -jar $(dirname $0)/nova3DPlugin.jar ~/Library/Preferences/Chitubox/zipTmpDir/

# osascript -e 'display dialog "script was called" with title "42"' 
```

Otherwise the plugin can not open file "nova3d-reference_slice.conf",  and output:

```
java.nio.file.NoSuchFileException: nova3d-reference_slice.conf
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at nova3DPlugin.main(nova3DPlugin.java:186)
```
